# This playbook is aimed to migrate all the devices, configlets and containers from an on-prem CVP to CVaaS
# Author: Philippe Bureau
# This playbook was modifed from the main branch to accomodate environments with different TerminAttr configs
- name: "Fetch CV on-prem device inventory and generate CVaaS onboarding token"
  hosts: cv_server
  connection: local
  gather_facts: no
  vars:
    cvaas_api: https://www.cv-prod-na-northeast1-b.arista.io/api/v3/services/admin.Enrollment/AddEnrollmentToken # change the URL to the right CVaaS instance
    cvaas_token: "{{lookup('file', '~/cvaas_arista_ce_canada.tok')}}"
    cvp_device_api: "https://10.18.156.165/cvpservice/inventory/devices?provisioned=true" # change the IP to the right CVP On-prem instance
    cvp_token: "{{lookup('file', '~/ACT_AVD_CI_EXTENDED.tok')}}"
  tasks:
  - name: 'Collect devices facts from {{inventory_hostname}}'
    tags: [ facts ]
    arista.cvp.cv_facts_v3:
      facts:
        - devices
        - configlets
        - containers
    register: facts_devices
  - name: "Get Current Device Inventory Data From CVP REST API"
    tags: [ facts ]
    ansible.builtin.uri:
      url: "{{ cvp_device_api }}"
      method: GET
      headers:
        Accept: "application/json"
        Cookie: "access_token={{ cvp_token }}"
      validate_certs: no
      return_content: yes
    register: current_cvp_devices_api_result
    until: current_cvp_devices_api_result.status == 200
    retries: 10
    delay: 2
  # Build list of device IPs from the inventory REST API call
  - name: "Building list of IP addresses"
    tags: [ facts ]
    set_fact:
      device_inventory: "{{ device_inventory | default([]) + [item.ipAddress] }}"
    with_items: "{{ current_cvp_devices_api_result.content  }}"
  - name: Concatenating device_inventory
    tags: [ facts ]
    set_fact:
      device_inventory_list: "{{ device_inventory | join('\n') }}"
  - name: "Building temporary device inventory"
    tags: [ facts ]
    copy:
      content: "{{ device_inventory_list }}"
      dest: "./inventory/onprem_devices.yaml"
    delegate_to: localhost
  - name: "Update onprem_devices.yaml file with group tag..."
    tags: [ facts ]
    lineinfile:
      path: "./inventory/onprem_devices.yaml"
      line: '[onprem_devices]'
      insertbefore: BOF

  - name: "Generating TerminAttr onboarding token on CVaaS instance"
    tags: [ facts ]
    ansible.builtin.uri:
      url: "{{ cvaas_api }}"
      method: POST
      headers:
        Accept: "application/json"
        Cookie: "access_token={{ cvaas_token }}"
      validate_certs: no
      return_content: yes
      body: '{"enrollmentToken": {"reenrollDevices": ["*"], "validFor": "720h"}}'
    register: cv_onboarding_token
    until: cv_onboarding_token.status == 200
    retries: 10
    delay: 2
  # Writing cvaas token to file
  - name: "Parsing CVaaS token"
    tags: [ facts ]
    set_fact:
      cv_onboarding_token: "{{ cv_onboarding_token.content | list | join }}"
  - name: "Writing CVaaS token to file"
    tags: [ facts ]
    copy:
      content: "{{ cv_onboarding_token[0].enrollmentToken.token }}"
      dest: "./cv-onboarding-token"

- name: Backing up CVP Facts
  hosts: localhost
  connection: local
  vars:
    cv_facts_dir: "cv_facts"
    documentation_dir: "documentation"
  tasks:
  - name: Create required output directories if not present
    tags: [ facts ]
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
    loop:
      - "{{ documentation_dir }}"
      - "{{ cv_facts_dir }}"
    delegate_to: localhost
    run_once: true

  - name: "Writing on-prem device facts from {{inventory_hostname}} to file"
    tags: [ facts ]
    copy:
      content: "{{ hostvars['cv_server'].facts_devices.data.cvp_devices |  to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
      dest: "{{ cv_facts_dir }}/cvp_devices.yaml"
    delegate_to: localhost
  - name: "Writing on-prem container facts from {{inventory_hostname}} to file"
    tags: [ facts ]
    copy:
      content: "{{ hostvars['cv_server'].facts_devices.data.cvp_containers |  to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
      dest: "{{ cv_facts_dir }}/cvp_containers.yaml"
    delegate_to: localhost
  - name: "Writing on-prem configlet facts from {{inventory_hostname}} to file"
    tags: [ facts ]
    copy:
      content: "{{ hostvars['cv_server'].facts_devices.data.cvp_configlets |  to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
      dest: "{{ cv_facts_dir }}/cvp_configlets.yaml"
    delegate_to: localhost

- name: "Copying the CVaaS token and reconfiguring TerminAttr on default vrf devices"
  hosts: default_vrf
  vars:
    ansible_user: cvpadmin
    ansible_password: arista123 # TO BE CHANGED
    ansible_connection: network_cli
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_network_os: eos
    ansible_httpapi_port: 443
    ansible_python_interpreter: $(which python3)
  tasks:
  - name: Copy CVaaS token
    tags: [ deploy ]
    net_put:
      src: "./cv-onboarding-token"
      dest: "/tmp/cv-onboarding-token"
  - name: "Configuring TerminAttr on {{ inventory_hostname }}"
    tags: [ deploy ]
    eos_command:
      commands:
        - "enable"
        - "config"
        - "daemon TerminAttr"
        - "exec /usr/bin/TerminAttr -cvaddr=apiserver.cv-prod-na-northeast1-b.arista.io:443 -disableaaa -cvcompression=gzip -taillogs -cvauth=token-secure,/tmp/cv-onboarding-token -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
        - "shut"
        - "no shut"

- name: "Copying the CVaaS token and reconfiguring TerminAttr on MGMT vrf devices"
  hosts: mgmt_vrf
  vars:
    ansible_user: cvpadmin
    ansible_password: arista123 # TO BE CHANGED
    ansible_connection: network_cli
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_network_os: eos
    ansible_httpapi_port: 443
    ansible_python_interpreter: $(which python3)
  tasks:
  - name: Copy CVaaS token
    tags: [ deploy ]
    net_put:
      src: "./cv-onboarding-token"
      dest: "/tmp/cv-onboarding-token"
  - name: "Configuring TerminAttr on {{ inventory_hostname }}"
    tags: [ deploy ]
    eos_command:
      commands:
        - "enable"
        - "config"
        - "daemon TerminAttr"
        - "exec /usr/bin/TerminAttr -cvaddr=apiserver.cv-prod-na-northeast1-b.arista.io:443 -disableaaa -cvcompression=gzip -cvvrf=MGMT -taillogs -cvauth=token-secure,/tmp/cv-onboarding-token -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
        - "shut"
        - "no shut"

- name: "CVaaS - upload configlets, create container hierarchy, move devices to their target containers and assign configlets"
  hosts: cvaas
  connection: local
  gather_facts: no
  tasks:
  - name: "Push configlets to CVaaS"
    tags: [ deploy, configlets ]
    arista.cvp.cv_configlet_v3:
      configlets: "{{ lookup('file', 'cv_facts/cvp_configlets.yaml') | from_yaml }}"
      state: present
    delegate_to: cvaas
  - name: "Generate container hierarchy"
    tags: [ deploy ]
    arista.cvp.cv_container_v3:
      topology: "{{ lookup('file', 'cv_facts/cvp_containers.yaml') | from_yaml }}"
      state: present
  - name: "Move devices to target containers and assign configlets"
    tags: [ deploy ]
    arista.cvp.cv_device_v3:
      devices: "{{lookup('file', 'cv_facts/cvp_devices.yaml') | from_yaml }}"
      state: present
      search_key: fqdn
    delegate_to: cvaas
