---
- name: "Fetch CV on-prem device inventory and generate CVaaS and CV onboarding tokens"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cvaas_api: https://www.cv-prod-us-central1-c.arista.io/api/v3/services/admin.Enrollment/AddEnrollmentToken # change the URL to the right CVaaS instance
    cvaas_token: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjcyMzEyODYwODY2NTAwNDY0MTYsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3MTcyNjY5NTUsImlhdCI6MTY4NzI4NjE2NCwib2dpIjo3MjMxMjg2MDg2NjUwMDQ0MzI4LCJvZ24iOiJmb3huZXdzLWNsb3VkdGVzdCIsInNpZCI6ImViMjM3ZjgyNmU3NjZkNzExZTA3ODk4OTFlOWYwYWVmOWUzYjY1YTE5YTQ4NjdmNDAxNzc2YjVhZDhkNTBiMDEtMU1adDNUUXEzTjU1SDh6SGYwV3ZfTldQMHlWUGhDaWpfVjRlbWdjYiJ9.47s0kGLJSHuxwta555mZUwVE6OZTRMr6ByX7WGyP3VO2DQQ1Hlg0WFwncXy71eDu5MmGVJ6eXj_J92lE2dct_Q"
    cvp_device_api: "https://10.255.64.179/cvpservice/inventory/devices?provisioned=true" # change the IP to the right CVP On-prem instance
    cvp_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjcyNDY3ODk2Mzg2ODgzNDIxNzQsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3MTc2MTE3ODIsImlhdCI6MTY4NzI4NTM4OCwic2lkIjoiZDQxMWE2MDE4Y2YxNTBmYzBhN2QwNTFiNjhiMGVjYWRiMzA1NzRjYjBkMzllNGFlZWY0MjI0NzIxMDk2ZmYwYi14azZlU29fOGZnVV90WnZoWG5Hd0lVdWkwQXA0eUwySXZYNHc1UlF0In0.q-XY15jOAowCnbvxv5-E6hxXrAfwgNVS7qtizV9nRHGnYBzM9ng4kystMxBidDGTSMcZwy8tBwjfUogr1NeNb4bzMJPonDRLTVW3OXpzGJcznSnqXuSSW8s_jVocC5Ax8RmGP_I0lpeH3KkNeGpeI0LnlTjZQRgabM2KT37mYYR5Ym2N8x5wR_cVnEv-NlF-Px9Sqrd3APTXgNXLa_Fv2kr8Gy52Hk9Jy99wYbbLzSAR8fidW7LmMdbR2gkVd2LxBP2tSHXvfdGxpkKOpJmzdEYHvbEQZnm1vWPLscKbw8iET_gn-nsVbsMdsFl5i_h4jQipGH8cLlRNXCy7axw86nSWYaolYq70eGpw7g1zjN863R3XDXQyFg9f7Z-4XJFRXC2v1lEqLS8QYKOPtoQyJ86KSl4eyNZW_eSFvOtjbP7wV3LvKEOvPdv6i_iQ5u42_sc62Q24mMXyzmW4LAoGM0pQf66rlBPl5myN3hpWjoxUfe4DhpC9Gl9EP0nUD3svSyhcAVM-nbowJEPgCWK0hM4tVDhuLX8ApJrJWHYV5rWBhT3g4uTTQnW14638DQFCIZG_Ak8qorsTf8vGWKd-rDMYe9JhWlnYSUnjJvIEdHqhLVJk_80diUunKdmFyV9Wm-QvfGBF-qcqfnajbxFUonDsnJl7B_mzvwR_xxAsYvM"
    cvp_token_api: "https://10.255.64.179/cvpservice/enroll/createToken"
  tasks:
  - name: "Generating TerminAttr onboarding token on CVaaS instance"
    tags: [build]
    ansible.builtin.uri:
      url: "{{ cvaas_api }}"
      method: POST
      headers:
        Accept: "application/json"
        Cookie: "access_token={{ cvaas_token }}"
      validate_certs: no
      return_content: yes
      body: '{"enrollmentToken": {"reenrollDevices": ["*"], "validFor": "720h"}}'
    register: cv_onboarding_token
    until: cv_onboarding_token.status == 200
    retries: 10
    delay: 2
  # Writing cvaas token to file
  - name: "Parsing CVaaS token"
    tags: [build]
    set_fact:
      cv_onboarding_token: "{{ cv_onboarding_token.content | list | join }}"
  - name: "Writing CVaaS token to file"
    tags: [build]
    copy:
      content: "{{ cv_onboarding_token[0].enrollmentToken.token }}"
      dest: "./cv-onboarding-token"
  - name: "Generating TerminAttr onboarding token on onprem instance"
    tags: [build]
    ansible.builtin.uri:
      url: "{{ cvp_token_api }}"
      method: POST
      headers:
        Accept: "application/json"
        Cookie: "access_token={{ cvp_token }}"
      validate_certs: no
      return_content: yes
      body: '{"reenrollDevices": ["*"], "duration": "720h"}'
    register: token
    until: token.status == 200
    retries: 10
    delay: 2
  # Writing onprem token to file
  - name: "Parsing CVP on-prem token"
    tags: [build]
    set_fact:
      token: "{{ token.content | list | join }}"
  - name: "Writing CVaaS token to file"
    tags: [build]
    copy:
      content: "{{ token.data }}"
      dest: "./token"

# Build device inventory
  - name: "Get Current Device Inventory Data From CVP REST API"
    tags: [build]
    ansible.builtin.uri:
      url: "{{ cvp_device_api }}"
      method: GET
      headers:
        Accept: "application/json"
        Cookie: "access_token={{ cvp_token }}"
      validate_certs: no
      return_content: yes
    register: current_cvp_devices_api_result
    until: current_cvp_devices_api_result.status == 200
    retries: 10
    delay: 2
  - name: "Building list of IP addresses"
    tags: [build]
    set_fact:
      device_inventory: "{{ device_inventory | default([]) + [item.ipAddress] }}"
    with_items: "{{ current_cvp_devices_api_result.content  }}"
  - name: Concatenating device_inventory
    tags: [build]
    set_fact:
      device_inventory_list: "{{ device_inventory | join('\n') }}"
  - name: "Building temporary device inventory"
    tags: [build]
    copy:
      content: "{{ device_inventory_list }}"
      dest: "./inventory/onprem_devices.yaml"
    delegate_to: localhost
  - name: "Update onprem_devices.yaml file with group tag..."
    tags: [build]
    lineinfile:
      path: "./inventory/onprem_devices.yaml"
      line: '[onprem_devices]'
      insertbefore: BOF

- hosts: onprem_devices
  vars:
    ansible_user: cvpadmin #make sure this user has privilege for scp (aaa authorization exec ...)
    ansible_password: arista123
    ansible_connection: network_cli
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_network_os: eos
    ansible_httpapi_port: 443
    ansible_python_interpreter: $(which python3) 
  tasks:
  - name: Copy on-prem token
    tags: [deploy]
    net_put:
       src: "./token"
       dest: "/tmp/token"
  - name: Copy cvaas token
    tags: [deploy]
    net_put:
       src: "./cv-onboarding-token"
       dest: "/tmp/cv-onboarding-token"
  - name: restart TerminAttr
    tags: [deploy]
    eos_command:
      commands:
        - "enable"
        - "config"
        - "daemon TerminAttr"
        - "exec /usr/bin/TerminAttr -cvopt cvaas.addr=apiserver.arista.io:443 -cvopt cvaas.auth=token-secure,/tmp/cv-onboarding-token -cvopt onprem.addr=192.168.0.5:9910 -cvopt onprem.auth=token,/tmp/token -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs -disableaaa"
        - "shut"
        - "no shut"