---
all:
  children:
    CVP:
      hosts:
        cvaas:
          ansible_httpapi_host: www.cv-prod-na-northeast1-b.arista.io
          ansible_host: www.cv-prod-na-northeast1-b.arista.io
          ansible_user: cvaas
          ansible_password: "{{ lookup('file', './tokens/cvaas.tok')}}"
          ansible_become: True
          ansible_become_method: enable
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: False
          ansible_network_os: eos
          ansible_httpapi_port: 443
        cv_server:
          ansible_httpapi_host: 192.168.0.5
          ansible_host: 192.168.0.5
          ansible_user: cvpadmin
          ansible_password: arista123
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: False
          ansible_network_os: eos
          ansible_httpapi_port: 443
          ansible_python_interpreter: $(which python3)
